import Head from "next/head";
import Image from "next/image";
import { SignUp } from "./auth/signin";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={" bg-gradient-to-tr from-pink-500 to-blue-600"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
    </div>
  );
}
